id: project-maestro-render
namespace: ai.cto
description: "Complete AI CTO workflow orchestrated by Kestra on Render"

inputs:
  - id: idea
    type: STRING
    required: true
    description: Product idea description
  - id: constraints
    type: JSON
    required: false
    description: Business constraints
  - id: callbackUrl
    type: STRING
    required: false
    description: Callback URL for workflow updates

tasks:
  # Validate input
  - id: validate_input
    type: io.kestra.plugin.core.log.Log
    description: "Validate workflow input"
    message: "Starting AI CTO workflow for: {{ inputs.idea }}"

  # Notify workflow start
  - id: notify_start
    type: io.kestra.plugin.core.http.Request
    description: "Notify workflow start"
    method: POST
    uri: "{{ inputs.callbackUrl | default('http://localhost:3000/api/workflow/callback') }}"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "status": "started",
        "workflowId": "{{ execution.id }}",
        "stage": "product_analysis",
        "timestamp": "{{ execution.startDate }}"
      }
    ignoreFailure: true

  # Product Analysis - Call Oumi Agent on Vercel
  - id: product_analysis
    type: io.kestra.plugin.core.http.Request
    description: "Analyze product using Oumi agent on Vercel"
    method: POST
    uri: "{{ env.VERCEL_URL | default('http://localhost:3000') }}/api/oumi/analyze"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "idea": "{{ inputs.idea }}",
        "constraints": {{ inputs.constraints | default({}) | to_json }}
      }
    outputFormat: JSON
    validStatus: [200, 201]

  # Architecture Design
  - id: architecture_design
    type: io.kestra.plugin.core.http.Request
    description: "Design technical architecture"
    method: POST
    uri: "{{ env.VERCEL_URL | default('http://localhost:3000') }}/api/oumi/architecture"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "productSpec": {{ outputs.product_analysis.body.data | to_json }}
      }
    outputFormat: JSON
    validStatus: [200, 201]
    dependsOn:
      - product_analysis

  # Code Generation
  - id: code_generation
    type: io.kestra.plugin.core.http.Request
    description: "Generate code using Cline automation"
    method: POST
    uri: "{{ env.VERCEL_URL | default('http://localhost:3000') }}/api/cline/generate"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "architecture": {{ outputs.architecture_design.body.data | to_json }},
        "taskBreakdown": {{ outputs.product_analysis.body.data.developmentPlan | default({}) | to_json }},
        "projectName": "{{ outputs.product_analysis.body.data.productSpecification.name | default('generated-project') }}",
        "workflowId": "{{ execution.id }}"
      }
    outputFormat: JSON
    validStatus: [200, 201]
    dependsOn:
      - architecture_design

  # Create GitHub Repository
  - id: create_github_repo
    type: io.kestra.plugin.core.http.Request
    description: "Create GitHub repository"
    method: POST
    uri: "{{ env.VERCEL_URL | default('http://localhost:3000') }}/api/github/create"
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ env.GITHUB_TOKEN }}"
    body: |
      {
        "projectName": "{{ outputs.product_analysis.body.data.productSpecification.name | default('generated-project') }}",
        "projectPath": "{{ outputs.code_generation.body.data.projectPath | default('/tmp/project') }}",
        "description": "Generated by Project Maestro AI CTO - Workflow: {{ execution.id }}"
      }
    outputFormat: JSON
    validStatus: [200, 201]
    dependsOn:
      - code_generation

  # Trigger Vercel Deployment
  - id: trigger_vercel_deploy
    type: io.kestra.plugin.core.http.Request
    description: "Trigger Vercel deployment via webhook"
    method: POST
    uri: "{{ env.VERCEL_URL | default('http://localhost:3000') }}/api/vercel/deploy"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "workflowId": "{{ execution.id }}",
        "projectName": "{{ outputs.product_analysis.body.data.productSpecification.name | default('generated-project') }}",
        "repositoryUrl": "{{ outputs.create_github_repo.body.data.repositoryUrl | default('') }}"
      }
    outputFormat: JSON
    validStatus: [200, 201]
    dependsOn:
      - create_github_repo

  # Notify completion
  - id: notify_completion
    type: io.kestra.plugin.core.http.Request
    description: "Notify workflow completion"
    method: POST
    uri: "{{ inputs.callbackUrl | default('http://localhost:3000/api/workflow/callback') }}"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "status": "completed",
        "workflowId": "{{ execution.id }}",
        "deploymentUrl": "{{ outputs.trigger_vercel_deploy.body.data.deploymentUrl | default('') }}",
        "githubUrl": "{{ outputs.create_github_repo.body.data.repositoryUrl | default('') }}",
        "projectName": "{{ outputs.product_analysis.body.data.productSpecification.name | default('generated-project') }}",
        "timestamp": "{{ execution.endDate }}"
      }
    ignoreFailure: true
    dependsOn:
      - trigger_vercel_deploy

  # Final summary log
  - id: completion_summary
    type: io.kestra.plugin.core.log.Log
    description: "Workflow completion summary"
    message: |
      Project Maestro workflow completed successfully!
      - Execution ID: {{ execution.id }}
      - Project: {{ outputs.product_analysis.body.data.productSpecification.name | default('N/A') }}
      - Deployment: {{ outputs.trigger_vercel_deploy.body.data.deploymentUrl | default('N/A') }}
      - GitHub: {{ outputs.create_github_repo.body.data.repositoryUrl | default('N/A') }}
    dependsOn:
      - notify_completion

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    description: "Webhook trigger from Vercel frontend"
    key: "{{ env.WEBHOOK_KEY }}"

